# Generated by Django 4.2.6 on 2023-10-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 존재하는 이메일 주소입니다.'}, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
